# test_sub_sim_file.py
# Tests for sub_sim_file function
# Copyright (C) 2020-2026 University of California
# -----------------------------------------------------------------------------
# This information is free; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This work is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# For a copy of the GNU General Public License, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
# -----------------------------------------------------------------------------

import pytest
import os
import iwfm


def create_sim_file_content(has_lake=False):
    """Create mock simulation main input file content.

    Based on C2VSimCG.in format:
    - Comment lines start with 'C', 'c', '*', or '#'
    - Data lines start with whitespace
    - '/' marks end of record
    - 3 title lines after comments, then file paths
    """
    lake_line = "  Lake\\Model_Lake.dat                              / 4: LAKE COMPONENT MAIN FILE" if has_lake else "                                                    / 4: LAKE COMPONENT MAIN FILE"

    content = """C Main simulation input file
C
                 Historical Simulation, Water Years 1922-2015
                         Central Valley, California
                    Simulation v.R383-2015-CG 2016.09.26
C-------------------------------------------------------------------------------
C    FILE NAME                                      DESCRIPTION
C-------------------------------------------------------------------------------
  C2VSimCG_PreprocessorOut.bin                      / 1: BINARY INPUT GENERATED BY PRE-PROCESSOR
  Groundwater\\C2VSimCG_Groundwater.dat             / 2: GROUNDWATER COMPONENT MAIN FILE
  Streams\\C2VSimCG_Streams.dat                     / 3: STREAM COMPONENT MAIN FILE
""" + lake_line + """
  RootZone\\C2VSimCG_RootZone.dat                   / 5: ROOT ZONE COMPONENT MAIN FILE
  C2VSimCG_SWatersheds.dat                          / 6: SMALL WATERSHED COMPONENT MAIN FILE
  C2VSimCG_Unsat.dat                                / 7: UNSATURATED ZONE COMPONENT MAIN FILE
  C2VSimCG_IrrFrac.dat                              / 8: IRRIGATION FRACTIONS DATA FILE
  C2VSimCG_SupplyAdj.dat                            / 9: SUPPLY ADJUSTMENT DATA FILE
C More content follows..."""
    return content


def create_sim_dict_new(tmp_path, prefix='SubModel'):
    """Create a dictionary of new submodel file names."""
    return {
        'sim_name': str(tmp_path / f'{prefix}.in'),
        'preout': f'{prefix}_PreprocessorOut.bin',
        'gw_file': f'Groundwater\\{prefix}_Groundwater.dat',
        'stream_file': f'Streams\\{prefix}_Streams.dat',
        'lake_file': f'Lake\\{prefix}_Lake.dat',
        'root_file': f'RootZone\\{prefix}_RootZone.dat',
        'swshed_file': f'{prefix}_SWatersheds.dat',
        'unsat_file': f'{prefix}_Unsat.dat',
    }


class TestSubSimFileBasic:
    """Basic functionality tests for sub_sim_file."""

    def test_creates_output_file(self, tmp_path):
        """Test that output file is created."""
        # Create input file
        input_file = tmp_path / 'old_sim.in'
        input_file.write_text(create_sim_file_content())

        sim_dict_new = create_sim_dict_new(tmp_path)

        iwfm.sub_sim_file(str(input_file), sim_dict_new, has_lake=False)

        assert os.path.exists(sim_dict_new['sim_name'])

    def test_output_contains_new_preout(self, tmp_path):
        """Test that output file contains new preprocessor output filename."""
        input_file = tmp_path / 'old_sim.in'
        input_file.write_text(create_sim_file_content())

        sim_dict_new = create_sim_dict_new(tmp_path)

        iwfm.sub_sim_file(str(input_file), sim_dict_new, has_lake=False)

        with open(sim_dict_new['sim_name'], 'r') as f:
            content = f.read()

        assert sim_dict_new['preout'] in content
        assert 'C2VSimCG_PreprocessorOut.bin' not in content

    def test_output_contains_new_gw_file(self, tmp_path):
        """Test that output file contains new groundwater filename."""
        input_file = tmp_path / 'old_sim.in'
        input_file.write_text(create_sim_file_content())

        sim_dict_new = create_sim_dict_new(tmp_path)

        iwfm.sub_sim_file(str(input_file), sim_dict_new, has_lake=False)

        with open(sim_dict_new['sim_name'], 'r') as f:
            content = f.read()

        assert sim_dict_new['gw_file'] in content

    def test_output_contains_new_stream_file(self, tmp_path):
        """Test that output file contains new stream filename."""
        input_file = tmp_path / 'old_sim.in'
        input_file.write_text(create_sim_file_content())

        sim_dict_new = create_sim_dict_new(tmp_path)

        iwfm.sub_sim_file(str(input_file), sim_dict_new, has_lake=False)

        with open(sim_dict_new['sim_name'], 'r') as f:
            content = f.read()

        assert sim_dict_new['stream_file'] in content

    def test_output_contains_new_root_file(self, tmp_path):
        """Test that output file contains new rootzone filename."""
        input_file = tmp_path / 'old_sim.in'
        input_file.write_text(create_sim_file_content())

        sim_dict_new = create_sim_dict_new(tmp_path)

        iwfm.sub_sim_file(str(input_file), sim_dict_new, has_lake=False)

        with open(sim_dict_new['sim_name'], 'r') as f:
            content = f.read()

        assert sim_dict_new['root_file'] in content

    def test_output_contains_new_swshed_file(self, tmp_path):
        """Test that output file contains new small watersheds filename."""
        input_file = tmp_path / 'old_sim.in'
        input_file.write_text(create_sim_file_content())

        sim_dict_new = create_sim_dict_new(tmp_path)

        iwfm.sub_sim_file(str(input_file), sim_dict_new, has_lake=False)

        with open(sim_dict_new['sim_name'], 'r') as f:
            content = f.read()

        assert sim_dict_new['swshed_file'] in content

    def test_output_contains_new_unsat_file(self, tmp_path):
        """Test that output file contains new unsaturated zone filename."""
        input_file = tmp_path / 'old_sim.in'
        input_file.write_text(create_sim_file_content())

        sim_dict_new = create_sim_dict_new(tmp_path)

        iwfm.sub_sim_file(str(input_file), sim_dict_new, has_lake=False)

        with open(sim_dict_new['sim_name'], 'r') as f:
            content = f.read()

        assert sim_dict_new['unsat_file'] in content

    def test_preserves_comments(self, tmp_path):
        """Test that comments are preserved in output."""
        input_file = tmp_path / 'old_sim.in'
        input_file.write_text(create_sim_file_content())

        sim_dict_new = create_sim_dict_new(tmp_path)

        iwfm.sub_sim_file(str(input_file), sim_dict_new, has_lake=False)

        with open(sim_dict_new['sim_name'], 'r') as f:
            content = f.read()

        assert 'C Main simulation input file' in content

    def test_preserves_title_lines(self, tmp_path):
        """Test that title lines are preserved in output."""
        input_file = tmp_path / 'old_sim.in'
        input_file.write_text(create_sim_file_content())

        sim_dict_new = create_sim_dict_new(tmp_path)

        iwfm.sub_sim_file(str(input_file), sim_dict_new, has_lake=False)

        with open(sim_dict_new['sim_name'], 'r') as f:
            content = f.read()

        assert 'Historical Simulation' in content
        assert 'Central Valley, California' in content

    def test_preserves_file_descriptions(self, tmp_path):
        """Test that file descriptions (after /) are preserved."""
        input_file = tmp_path / 'old_sim.in'
        input_file.write_text(create_sim_file_content())

        sim_dict_new = create_sim_dict_new(tmp_path)

        iwfm.sub_sim_file(str(input_file), sim_dict_new, has_lake=False)

        with open(sim_dict_new['sim_name'], 'r') as f:
            content = f.read()

        assert '1: BINARY INPUT GENERATED BY PRE-PROCESSOR' in content
        assert '2: GROUNDWATER COMPONENT MAIN FILE' in content


class TestSubSimFileLake:
    """Tests for lake file handling in sub_sim_file."""

    def test_no_lake_skips_lake_line(self, tmp_path):
        """Test that lake line is skipped when has_lake=False."""
        input_file = tmp_path / 'old_sim.in'
        input_file.write_text(create_sim_file_content(has_lake=False))

        sim_dict_new = create_sim_dict_new(tmp_path)

        iwfm.sub_sim_file(str(input_file), sim_dict_new, has_lake=False)

        with open(sim_dict_new['sim_name'], 'r') as f:
            content = f.read()

        # Lake line should remain blank/unchanged
        assert sim_dict_new['lake_file'] not in content

    def test_with_lake_updates_lake_line(self, tmp_path):
        """Test that lake line is updated when has_lake=True."""
        input_file = tmp_path / 'old_sim.in'
        input_file.write_text(create_sim_file_content(has_lake=True))

        sim_dict_new = create_sim_dict_new(tmp_path)

        iwfm.sub_sim_file(str(input_file), sim_dict_new, has_lake=True)

        with open(sim_dict_new['sim_name'], 'r') as f:
            content = f.read()

        assert sim_dict_new['lake_file'] in content

    def test_with_lake_preserves_other_files(self, tmp_path):
        """Test that other files are still updated with has_lake=True."""
        input_file = tmp_path / 'old_sim.in'
        input_file.write_text(create_sim_file_content(has_lake=True))

        sim_dict_new = create_sim_dict_new(tmp_path)

        iwfm.sub_sim_file(str(input_file), sim_dict_new, has_lake=True)

        with open(sim_dict_new['sim_name'], 'r') as f:
            content = f.read()

        # All files should be updated
        assert sim_dict_new['preout'] in content
        assert sim_dict_new['gw_file'] in content
        assert sim_dict_new['stream_file'] in content
        assert sim_dict_new['root_file'] in content
        assert sim_dict_new['swshed_file'] in content
        assert sim_dict_new['unsat_file'] in content


class TestSubSimFileNotFound:
    """Tests for file not found handling."""

    def test_missing_input_file_raises_error(self, tmp_path):
        """Test that missing input file raises SystemExit."""
        sim_dict_new = create_sim_dict_new(tmp_path)

        with pytest.raises(SystemExit):  # file_test calls sys.exit() for missing files
            iwfm.sub_sim_file(str(tmp_path / 'nonexistent.in'), sim_dict_new)


class TestSubSimFileRealFormat:
    """Tests using more realistic IWFM file format."""

    def test_with_multiple_comment_styles(self, tmp_path):
        """Test handling of different comment styles (C, c, *, #)."""
        content = """C Main comment with C
c lowercase comment
* star comment
# hash comment
                 Title Line 1
                 Title Line 2
                 Title Line 3
C File section
  OldModel_PreprocessorOut.bin                      / 1: PREPROCESSOR OUTPUT
  Groundwater\\OldModel_Groundwater.dat             / 2: GROUNDWATER
  Streams\\OldModel_Streams.dat                     / 3: STREAMS
                                                    / 4: LAKE
  RootZone\\OldModel_RootZone.dat                   / 5: ROOTZONE
  OldModel_SWatersheds.dat                          / 6: SMALL WATERSHEDS
  OldModel_Unsat.dat                                / 7: UNSATURATED"""

        input_file = tmp_path / 'old_sim.in'
        input_file.write_text(content)

        sim_dict_new = create_sim_dict_new(tmp_path)

        iwfm.sub_sim_file(str(input_file), sim_dict_new, has_lake=False)

        with open(sim_dict_new['sim_name'], 'r') as f:
            output = f.read()

        # All new filenames should be present
        assert sim_dict_new['preout'] in output
        assert sim_dict_new['gw_file'] in output

    def test_preserves_content_after_files(self, tmp_path):
        """Test that content after the 7 file lines is preserved."""
        input_file = tmp_path / 'old_sim.in'
        input_file.write_text(create_sim_file_content())

        sim_dict_new = create_sim_dict_new(tmp_path)

        iwfm.sub_sim_file(str(input_file), sim_dict_new, has_lake=False)

        with open(sim_dict_new['sim_name'], 'r') as f:
            content = f.read()

        # Content after the 7 component files should be preserved
        assert '8: IRRIGATION FRACTIONS DATA FILE' in content
        assert '9: SUPPLY ADJUSTMENT DATA FILE' in content


class TestSubSimFileWithRealFile:
    """Tests using actual C2VSimCG.in file if available."""

    @pytest.fixture
    def real_sim_file(self):
        """Return path to real simulation file if it exists."""
        real_file = '/Volumes/MinEx/Documents/Dropbox/work/Programing/repos/iwfm-py/iwfm-tests/C2VSimCG-2021/Simulation/C2VSimCG.in'
        if os.path.exists(real_file):
            return real_file
        pytest.skip("Real C2VSimCG.in file not available")

    def test_with_real_file(self, tmp_path, real_sim_file):
        """Test sub_sim_file with real C2VSimCG.in file."""
        sim_dict_new = create_sim_dict_new(tmp_path, prefix='TestSubModel')

        iwfm.sub_sim_file(real_sim_file, sim_dict_new, has_lake=False)

        assert os.path.exists(sim_dict_new['sim_name'])

        with open(sim_dict_new['sim_name'], 'r') as f:
            content = f.read()

        # Verify new file names are in output
        assert sim_dict_new['preout'] in content
        assert sim_dict_new['gw_file'] in content
        assert sim_dict_new['stream_file'] in content
        assert sim_dict_new['root_file'] in content
        assert sim_dict_new['swshed_file'] in content
        assert sim_dict_new['unsat_file'] in content

        # Verify old file names are NOT in output (for the 7 component files)
        assert 'C2VSimCG_PreprocessorOut.bin' not in content

        # But simulation parameters should be preserved
        assert '09/30/1973_24:00' in content or 'BDT' in content


class TestSubSimFileEdgeCases:
    """Edge case tests for sub_sim_file."""

    def test_handles_minimal_file(self, tmp_path):
        """Test with minimal valid simulation file."""
        content = """C Comment
                 Title 1
                 Title 2
                 Title 3
  Old_Preproc.bin                                   / 1: PREPROC
  Old_GW.dat                                        / 2: GW
  Old_Streams.dat                                   / 3: STREAMS
                                                    / 4: LAKE
  Old_RZ.dat                                        / 5: ROOTZONE
  Old_SWS.dat                                       / 6: SWS
  Old_Unsat.dat                                     / 7: UNSAT"""

        input_file = tmp_path / 'minimal.in'
        input_file.write_text(content)

        sim_dict_new = create_sim_dict_new(tmp_path)

        iwfm.sub_sim_file(str(input_file), sim_dict_new, has_lake=False)

        assert os.path.exists(sim_dict_new['sim_name'])

        with open(sim_dict_new['sim_name'], 'r') as f:
            output = f.read()

        assert sim_dict_new['preout'] in output

    def test_handles_long_filenames(self, tmp_path):
        """Test with very long filenames in dictionary."""
        input_file = tmp_path / 'old_sim.in'
        input_file.write_text(create_sim_file_content())

        sim_dict_new = {
            'sim_name': str(tmp_path / 'output.in'),
            'preout': 'VeryLongSubModelNameForTesting_PreprocessorOut.bin',
            'gw_file': 'Groundwater\\VeryLongSubModelNameForTesting_Groundwater.dat',
            'stream_file': 'Streams\\VeryLongSubModelNameForTesting_Streams.dat',
            'lake_file': 'Lake\\VeryLongSubModelNameForTesting_Lake.dat',
            'root_file': 'RootZone\\VeryLongSubModelNameForTesting_RootZone.dat',
            'swshed_file': 'VeryLongSubModelNameForTesting_SWatersheds.dat',
            'unsat_file': 'VeryLongSubModelNameForTesting_Unsat.dat',
        }

        iwfm.sub_sim_file(str(input_file), sim_dict_new, has_lake=False)

        with open(sim_dict_new['sim_name'], 'r') as f:
            content = f.read()

        assert sim_dict_new['preout'] in content

    def test_returns_none(self, tmp_path):
        """Test that function returns None."""
        input_file = tmp_path / 'old_sim.in'
        input_file.write_text(create_sim_file_content())

        sim_dict_new = create_sim_dict_new(tmp_path)

        result = iwfm.sub_sim_file(str(input_file), sim_dict_new, has_lake=False)

        assert result is None

    def test_output_ends_with_newline(self, tmp_path):
        """Test that output file ends with blank line (IWFM convention)."""
        input_file = tmp_path / 'old_sim.in'
        input_file.write_text(create_sim_file_content())

        sim_dict_new = create_sim_dict_new(tmp_path)

        iwfm.sub_sim_file(str(input_file), sim_dict_new, has_lake=False)

        with open(sim_dict_new['sim_name'], 'r') as f:
            content = f.read()

        # Should end with newline (from appended blank line)
        assert content.endswith('\n')
